version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Use groups to consolidate updates into a larger PR
    versioning-strategy: increase-if-necessary
    groups:
      dev-dependencies:
        dependency-type: development
      minor-updates:
        update-types:
          - "minor"
          - "patch"