version: "3.7"

volumes:
  postgres:
  node_modules:

services:

  postgres:
    image: postgres:9.6.17
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgres
    ports:
      - target: 5432
        published: ${PUBLISH_PORT_POSTGRES}
        protocol: tcp
        mode: host

  # This container installs node modules into the node_modules volume.
  installer:
    image: node:16.16.0
    working_dir: /workspace
    command: npm ci
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: node_modules
        target: /workspace/node_modules

  # This container watches for changes and builds the application.
  builder:
    depends_on:
      - installer
    image: node:16.16.0
    working_dir: /workspace
    command: ./scripts/await.sh node_modules/.bin/lerna npm run build:development:chained
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: node_modules
        target: /workspace/node_modules

  # This container runs the server.
  server:
    depends_on:
      - builder
      - postgres
    image: node:16.16.0
    working_dir: /workspace
    command: ./scripts/await.sh node_modules/.bin/nodemon ./scripts/await.sh dist/server.js npm run start:development
    environment:
      NODE_ENV: development
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: node_modules
        target: /workspace/node_modules
    ports:
      - target: 80
        published: ${PUBLISH_PORT_HTTP}
        protocol: tcp
        mode: host
