version: "3.7"

volumes:
  postgres:

services:

  # This container runs the database.
  postgres:
    image: postgres:9.6.17
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgres
    ports:
      - target: 5432
        published: ${PUBLISH_PORT_POSTGRES}
        protocol: tcp
        mode: host
    user: postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 5s
      start_interval: 10s
      interval: 10s
      timeout: 3s
      retries: 3

  # This container installs node modules from the package-lock.json file.
  installer:
    image: node:16.16.0
    working_dir: /workspace

    # We would rather ignore scripts, but this repo depends on bcrypt, which
    # requires a build step.
    # command: npm ci --ignore-scripts
    command: scripts/install.sh

    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /workspace
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/package-lock.json"]
      start_period: 5s
      start_interval: 10s
      interval: 10s
      timeout: 3s
      retries: 6

  # This container watches for changes and builds the application.
  builder:
    depends_on:
      installer:
        condition: service_healthy
        restart: false
    image: node:16.16.0
    working_dir: /workspace
    command: npm run build:development:chained
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /workspace
    healthcheck:
      test: ["CMD", "test", "-f", "dist/server.js"]
      start_period: 5s
      start_interval: 10s
      interval: 10s
      timeout: 3s
      retries: 6

  # This container runs the server.
  server:
    depends_on:
      builder:
        condition: service_healthy
        restart: false
      postgres:
        condition: service_healthy
        restart: false
    image: node:16.16.0
    working_dir: /workspace
    command: npm run start:development
    environment:
      NODE_ENV: development
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    volumes:
      - type: bind
        source: .
        target: /workspace
    ports:
      - target: 80
        published: ${PUBLISH_PORT_HTTP}
        protocol: tcp
        mode: host
